### ISSUE TITLE
TrcCommonLib doesn't have the latest code

### ISSUE THREAD

**Issue by abhaybd** [trc492/TrcCommonLib#1]
Some classes do not have the latest versions of code. The latest versions should be available in the [FRC 2020 repo](https://github.com/trc492/Frc2020InfiniteRecharge), if I'm not mistaken. There are probably some changes here that are not present there, so they should be merged together, not necessarily just overridden.

A non-exhaustive list of examples:
- `TrcPath` is missing the methods `trapezoidVelocity()`, `getLastWaypoint()`, etc.
- `TrcWaypoint` is missing the method `getPositionPose()`
- `TrcHolonomicPurePursuitDrive` is missing a bugfix to the `getFollowingPoint()` method, as well as some logging code.

**Comment by abhaybd** [comment]
Once the latest code is merged, this type of code could be simplified using `TrcPath.relativeToStart()`
https://github.com/trc492/TrcCommonLib/blob/3f85a9b4d9ed14f8c872d9f4d4a1a2e9ff777d0a/command/CmdPurePursuitDrive.java#L71-L78

**Comment by trc492** [comment]
The code should now be in-sync with Frc2020.
